import java.util.ArrayList;
import java.util.Scanner;

public class Main {

  public static void main(String[] args) {

    System.out.print("Indtast postnummer: ");

    Scanner scan = new Scanner(System.in);

    int Postnr_input = scan.nextInt();

        ArrayList<Postinfo> array = new ArrayList<>();

    array.add(new Postinfo(2600 , "Glostrup"));
    array.add(new Postinfo(	800	,"	Høje Taastrup	"));
    array.add(new Postinfo(	900	,"	København C	"));
    array.add(new Postinfo(	917	,"	Københavns Pakkecent	"));
    array.add(new Postinfo(	960	,"	Udland	"));
    array.add(new Postinfo(	999	,"	København C	"));
    array.add(new Postinfo(	1000	,"	København K	"));
    array.add(new Postinfo(	1050	,"	København K	"));
    array.add(new Postinfo(	1051	,"	København K	"));
    array.add(new Postinfo(	1052	,"	København K	"));
    array.add(new Postinfo(	1053	,"	København K	"));
    array.add(new Postinfo(	1054	,"	København K	"));
    array.add(new Postinfo(	1055	,"	København K	"));
    array.add(new Postinfo(	1056	,"	København K	"));
    array.add(new Postinfo(	1057	,"	København K	"));
    array.add(new Postinfo(	1058	,"	København K	"));
    array.add(new Postinfo(	1059	,"	København K	"));
    array.add(new Postinfo(	1060	,"	København K	"));
    array.add(new Postinfo(	1061	,"	København K	"));
    array.add(new Postinfo(	1062	,"	København K	"));
    array.add(new Postinfo(	1063	,"	København K	"));
    array.add(new Postinfo(	1064	,"	København K	"));
    array.add(new Postinfo(	1065	,"	København K	"));
    array.add(new Postinfo(	1066	,"	København K	"));
    array.add(new Postinfo(	1067	,"	København K	"));
    array.add(new Postinfo(	1068	,"	København K	"));
    array.add(new Postinfo(	1069	,"	København K	"));
    array.add(new Postinfo(	1070	,"	København K	"));
    array.add(new Postinfo(	1071	,"	København K	"));
    array.add(new Postinfo(	1072	,"	København K	"));
    array.add(new Postinfo(	1073	,"	København K	"));
    array.add(new Postinfo(	1074	,"	København K	"));
    array.add(new Postinfo(	1092	,"	København K	"));
    array.add(new Postinfo(	1093	,"	København K	"));
    array.add(new Postinfo(	1095	,"	København K	"));
    array.add(new Postinfo(	1098	,"	København K	"));
    array.add(new Postinfo(	1100	,"	København K	"));
    array.add(new Postinfo(	1101	,"	København K	"));
    array.add(new Postinfo(	1102	,"	København K	"));
    array.add(new Postinfo(	1103	,"	København K	"));
    array.add(new Postinfo(	1104	,"	København K	"));
    array.add(new Postinfo(	1105	,"	København K	"));
    array.add(new Postinfo(	1106	,"	København K	"));
    array.add(new Postinfo(	1107	,"	København K	"));
    array.add(new Postinfo(	1110	,"	København K	"));
    array.add(new Postinfo(	1111	,"	København K	"));
    array.add(new Postinfo(	1112	,"	København K	"));
    array.add(new Postinfo(	1113	,"	København K	"));
    array.add(new Postinfo(	1114	,"	København K	"));
    array.add(new Postinfo(	1115	,"	København K	"));
    array.add(new Postinfo(	1116	,"	København K	"));
    array.add(new Postinfo(	1117	,"	København K	"));
    array.add(new Postinfo(	1118	,"	København K	"));
    array.add(new Postinfo(	1119	,"	København K	"));
    array.add(new Postinfo(	1120	,"	København K	"));
    array.add(new Postinfo(	1121	,"	København K	"));
    array.add(new Postinfo(	1122	,"	København K	"));
    array.add(new Postinfo(	1123	,"	København K	"));
    array.add(new Postinfo(	1124	,"	København K	"));
    array.add(new Postinfo(	1125	,"	København K	"));
    array.add(new Postinfo(	1126	,"	København K	"));
    array.add(new Postinfo(	1127	,"	København K	"));
    array.add(new Postinfo(	1128	,"	København K	"));
    array.add(new Postinfo(	1129	,"	København K	"));
    array.add(new Postinfo(	1130	,"	København K	"));
    array.add(new Postinfo(	1131	,"	København K	"));
    array.add(new Postinfo(	1140	,"	København K	"));
    array.add(new Postinfo(	1147	,"	København K	"));
    array.add(new Postinfo(	1148	,"	København K	"));
    array.add(new Postinfo(	1150	,"	København K	"));
    array.add(new Postinfo(	1151	,"	København K	"));
    array.add(new Postinfo(	1152	,"	København K	"));
    array.add(new Postinfo(	1153	,"	København K	"));
    array.add(new Postinfo(	1154	,"	København K	"));
    array.add(new Postinfo(	1155	,"	København K	"));
    array.add(new Postinfo(	1156	,"	København K	"));
    array.add(new Postinfo(	1157	,"	København K	"));
    array.add(new Postinfo(	1158	,"	København K	"));
    array.add(new Postinfo(	1159	,"	København K	"));
    array.add(new Postinfo(	1160	,"	København K	"));
    array.add(new Postinfo(	1161	,"	København K	"));
    array.add(new Postinfo(	1162	,"	København K	"));
    array.add(new Postinfo(	1164	,"	København K	"));
    array.add(new Postinfo(	1165	,"	København K	"));
    array.add(new Postinfo(	1166	,"	København K	"));
    array.add(new Postinfo(	1167	,"	København K	"));
    array.add(new Postinfo(	1168	,"	København K	"));
    array.add(new Postinfo(	1169	,"	København K	"));
    array.add(new Postinfo(	1170	,"	København K	"));
    array.add(new Postinfo(	1171	,"	København K	"));
    array.add(new Postinfo(	1172	,"	København K	"));
    array.add(new Postinfo(	1173	,"	København K	"));
    array.add(new Postinfo(	1174	,"	København K	"));
    array.add(new Postinfo(	1175	,"	København K	"));
    array.add(new Postinfo(	1200	,"	København K	"));
    array.add(new Postinfo(	1201	,"	København K	"));
    array.add(new Postinfo(	1202	,"	København K	"));
    array.add(new Postinfo(	1203	,"	København K	"));
    array.add(new Postinfo(	1204	,"	København K	"));
    array.add(new Postinfo(	1205	,"	København K	"));
    array.add(new Postinfo(	1206	,"	København K	"));
    array.add(new Postinfo(	1207	,"	København K	"));
    array.add(new Postinfo(	1208	,"	København K	"));
    array.add(new Postinfo(	1209	,"	København K	"));
    array.add(new Postinfo(	1210	,"	København K	"));
    array.add(new Postinfo(	1211	,"	København K	"));
    array.add(new Postinfo(	1213	,"	København K	"));
    array.add(new Postinfo(	1214	,"	København K	"));
    array.add(new Postinfo(	1215	,"	København K	"));
    array.add(new Postinfo(	1216	,"	København K	"));
    array.add(new Postinfo(	1217	,"	København K	"));
    array.add(new Postinfo(	1218	,"	København K	"));
    array.add(new Postinfo(	1219	,"	København K	"));
    array.add(new Postinfo(	1220	,"	København K	"));
    array.add(new Postinfo(	1221	,"	København K	"));
    array.add(new Postinfo(	1240	,"	København K	"));
    array.add(new Postinfo(	1250	,"	København K	"));
    array.add(new Postinfo(	1251	,"	København K	"));
    array.add(new Postinfo(	1253	,"	København K	"));
    array.add(new Postinfo(	1254	,"	København K	"));
    array.add(new Postinfo(	1255	,"	København K	"));
    array.add(new Postinfo(	1256	,"	København K	"));
    array.add(new Postinfo(	1257	,"	København K	"));
    array.add(new Postinfo(	1259	,"	København K	"));
    array.add(new Postinfo(	1260	,"	København K	"));
    array.add(new Postinfo(	1261	,"	København K	"));
    array.add(new Postinfo(	1263	,"	København K	"));
    array.add(new Postinfo(	1264	,"	København K	"));
    array.add(new Postinfo(	1265	,"	København K	"));
    array.add(new Postinfo(	1266	,"	København K	"));
    array.add(new Postinfo(	1267	,"	København K	"));
    array.add(new Postinfo(	1268	,"	København K	"));
    array.add(new Postinfo(	1270	,"	København K	"));
    array.add(new Postinfo(	1271	,"	København K	"));
    array.add(new Postinfo(	1291	,"	København K	"));
    array.add(new Postinfo(	1300	,"	København K	"));
    array.add(new Postinfo(	1301	,"	København K	"));
    array.add(new Postinfo(	1302	,"	København K	"));
    array.add(new Postinfo(	1303	,"	København K	"));
    array.add(new Postinfo(	1304	,"	København K	"));
    array.add(new Postinfo(	1306	,"	København K	"));
    array.add(new Postinfo(	1307	,"	København K	"));
    array.add(new Postinfo(	1308	,"	København K	"));
    array.add(new Postinfo(	1309	,"	København K	"));
    array.add(new Postinfo(	1310	,"	København K	"));
    array.add(new Postinfo(	1311	,"	København K	"));
    array.add(new Postinfo(	1312	,"	København K	"));
    array.add(new Postinfo(	1313	,"	København K	"));
    array.add(new Postinfo(	1314	,"	København K	"));
    array.add(new Postinfo(	1315	,"	København K	"));
    array.add(new Postinfo(	1316	,"	København K	"));
    array.add(new Postinfo(	1317	,"	København K	"));
    array.add(new Postinfo(	1318	,"	København K	"));
    array.add(new Postinfo(	1319	,"	København K	"));
    array.add(new Postinfo(	1320	,"	København K	"));
    array.add(new Postinfo(	1321	,"	København K	"));
    array.add(new Postinfo(	1322	,"	København K	"));
    array.add(new Postinfo(	1323	,"	København K	"));
    array.add(new Postinfo(	1324	,"	København K	"));
    array.add(new Postinfo(	1325	,"	København K	"));
    array.add(new Postinfo(	1326	,"	København K	"));
    array.add(new Postinfo(	1327	,"	København K	"));
    array.add(new Postinfo(	1328	,"	København K	"));
    array.add(new Postinfo(	1329	,"	København K	"));
    array.add(new Postinfo(	1350	,"	København K	"));
    array.add(new Postinfo(	1352	,"	København K	"));
    array.add(new Postinfo(	1353	,"	København K	"));
    array.add(new Postinfo(	1354	,"	København K	"));
    array.add(new Postinfo(	1355	,"	København K	"));
    array.add(new Postinfo(	1356	,"	København K	"));
    array.add(new Postinfo(	1357	,"	København K	"));
    array.add(new Postinfo(	1358	,"	København K	"));
    array.add(new Postinfo(	1359	,"	København K	"));
    array.add(new Postinfo(	1360	,"	København K	"));
    array.add(new Postinfo(	1361	,"	København K	"));
    array.add(new Postinfo(	1362	,"	København K	"));
    array.add(new Postinfo(	1363	,"	København K	"));
    array.add(new Postinfo(	1364	,"	København K	"));
    array.add(new Postinfo(	1365	,"	København K	"));
    array.add(new Postinfo(	1366	,"	København K	"));
    array.add(new Postinfo(	1367	,"	København K	"));
    array.add(new Postinfo(	1368	,"	København K	"));
    array.add(new Postinfo(	1369	,"	København K	"));
    array.add(new Postinfo(	1370	,"	København K	"));
    array.add(new Postinfo(	1371	,"	København K	"));
    array.add(new Postinfo(	1400	,"	København K	"));
    array.add(new Postinfo(	1401	,"	København K	"));
    array.add(new Postinfo(	1402	,"	København K	"));
    array.add(new Postinfo(	1403	,"	København K	"));
    array.add(new Postinfo(	1406	,"	København K	"));
    array.add(new Postinfo(	1407	,"	København K	"));
    array.add(new Postinfo(	1408	,"	København K	"));
    array.add(new Postinfo(	1409	,"	København K	"));
    array.add(new Postinfo(	1410	,"	København K	"));
    array.add(new Postinfo(	1411	,"	København K	"));
    array.add(new Postinfo(	1412	,"	København K	"));
    array.add(new Postinfo(	1413	,"	København K	"));
    array.add(new Postinfo(	1414	,"	København K	"));
    array.add(new Postinfo(	1415	,"	København K	"));
    array.add(new Postinfo(	1416	,"	København K	"));
    array.add(new Postinfo(	1417	,"	København K	"));
    array.add(new Postinfo(	1418	,"	København K	"));
    array.add(new Postinfo(	1419	,"	København K	"));
    array.add(new Postinfo(	1420	,"	København K	"));
    array.add(new Postinfo(	1421	,"	København K	"));
    array.add(new Postinfo(	1422	,"	København K	"));
    array.add(new Postinfo(	1423	,"	København K	"));
    array.add(new Postinfo(	1424	,"	København K	"));
    array.add(new Postinfo(	1425	,"	København K	"));
    array.add(new Postinfo(	1426	,"	København K	"));
    array.add(new Postinfo(	1427	,"	København K	"));
    array.add(new Postinfo(	1428	,"	København K	"));
    array.add(new Postinfo(	1429	,"	København K	"));
    array.add(new Postinfo(	1430	,"	København K	"));
    array.add(new Postinfo(	1431	,"	København K	"));
    array.add(new Postinfo(	1432	,"	København K	"));
    array.add(new Postinfo(	1433	,"	København K	"));
    array.add(new Postinfo(	1434	,"	København K	"));
    array.add(new Postinfo(	1435	,"	København K	"));
    array.add(new Postinfo(	1436	,"	København K	"));
    array.add(new Postinfo(	1437	,"	København K	"));
    array.add(new Postinfo(	1438	,"	København K	"));
    array.add(new Postinfo(	1439	,"	København K	"));
    array.add(new Postinfo(	1440	,"	København K	"));
    array.add(new Postinfo(	1441	,"	København K	"));
    array.add(new Postinfo(	1448	,"	København K	"));
    array.add(new Postinfo(	1450	,"	København K	"));
    array.add(new Postinfo(	1451	,"	København K	"));
    array.add(new Postinfo(	1452	,"	København K	"));
    array.add(new Postinfo(	1453	,"	København K	"));
    array.add(new Postinfo(	1454	,"	København K	"));
    array.add(new Postinfo(	1455	,"	København K	"));
    array.add(new Postinfo(	1456	,"	København K	"));
    array.add(new Postinfo(	1457	,"	København K	"));
    array.add(new Postinfo(	1458	,"	København K	"));
    array.add(new Postinfo(	1459	,"	København K	"));
    array.add(new Postinfo(	1460	,"	København K	"));
    array.add(new Postinfo(	1462	,"	København K	"));
    array.add(new Postinfo(	1463	,"	København K	"));
    array.add(new Postinfo(	1464	,"	København K	"));
    array.add(new Postinfo(	1466	,"	København K	"));
    array.add(new Postinfo(	1467	,"	København K	"));
    array.add(new Postinfo(	1468	,"	København K	"));
    array.add(new Postinfo(	1470	,"	København K	"));
    array.add(new Postinfo(	1471	,"	København K	"));
    array.add(new Postinfo(	1472	,"	København K	"));
    array.add(new Postinfo(	1500	,"	København V	"));
    array.add(new Postinfo(	1513	,"	Centraltastning	"));
    array.add(new Postinfo(	1532	,"	København V	"));
    array.add(new Postinfo(	1533	,"	København V	"));
    array.add(new Postinfo(	1550	,"	København V	"));
    array.add(new Postinfo(	1551	,"	København V	"));
    array.add(new Postinfo(	1552	,"	København V	"));
    array.add(new Postinfo(	1553	,"	København V	"));
    array.add(new Postinfo(	1554	,"	København V	"));
    array.add(new Postinfo(	1555	,"	København V	"));
    array.add(new Postinfo(	1556	,"	København V	"));
    array.add(new Postinfo(	1557	,"	København V	"));
    array.add(new Postinfo(	1558	,"	København V	"));
    array.add(new Postinfo(	1559	,"	København V	"));
    array.add(new Postinfo(	1560	,"	København V	"));
    array.add(new Postinfo(	1561	,"	København V	"));
    array.add(new Postinfo(	1562	,"	København V	"));
    array.add(new Postinfo(	1563	,"	København V	"));
    array.add(new Postinfo(	1564	,"	København V	"));
    array.add(new Postinfo(	1566	,"	København V	"));
    array.add(new Postinfo(	1567	,"	København V	"));
    array.add(new Postinfo(	1568	,"	København V	"));
    array.add(new Postinfo(	1569	,"	København V	"));
    array.add(new Postinfo(	1570	,"	København V	"));
    array.add(new Postinfo(	1571	,"	København V	"));
    array.add(new Postinfo(	1572	,"	København V	"));
    array.add(new Postinfo(	1573	,"	København V	"));
    array.add(new Postinfo(	1574	,"	København V	"));
    array.add(new Postinfo(	1575	,"	København V	"));
    array.add(new Postinfo(	1576	,"	København V	"));
    array.add(new Postinfo(	1577	,"	København V	"));
    array.add(new Postinfo(	1592	,"	København V	"));
    array.add(new Postinfo(	1599	,"	København V	"));
    array.add(new Postinfo(	1600	,"	København V	"));
    array.add(new Postinfo(	1601	,"	København V	"));
    array.add(new Postinfo(	1602	,"	København V	"));
    array.add(new Postinfo(	1603	,"	København V	"));
    array.add(new Postinfo(	1604	,"	København V	"));
    array.add(new Postinfo(	1606	,"	København V	"));
    array.add(new Postinfo(	1607	,"	København V	"));
    array.add(new Postinfo(	1608	,"	København V	"));
    array.add(new Postinfo(	1609	,"	København V	"));
    array.add(new Postinfo(	1610	,"	København V	"));
    array.add(new Postinfo(	1611	,"	København V	"));
    array.add(new Postinfo(	1612	,"	København V	"));
    array.add(new Postinfo(	1613	,"	København V	"));
    array.add(new Postinfo(	1614	,"	København V	"));
    array.add(new Postinfo(	1615	,"	København V	"));
    array.add(new Postinfo(	1616	,"	København V	"));
    array.add(new Postinfo(	1617	,"	København V	"));
    array.add(new Postinfo(	1618	,"	København V	"));
    array.add(new Postinfo(	1619	,"	København V	"));
    array.add(new Postinfo(	1620	,"	København V	"));
    array.add(new Postinfo(	1621	,"	København V	"));
    array.add(new Postinfo(	1622	,"	København V	"));
    array.add(new Postinfo(	1623	,"	København V	"));
    array.add(new Postinfo(	1624	,"	København V	"));
    array.add(new Postinfo(	1630	,"	København V	"));
    array.add(new Postinfo(	1631	,"	København V	"));
    array.add(new Postinfo(	1632	,"	København V	"));
    array.add(new Postinfo(	1633	,"	København V	"));
    array.add(new Postinfo(	1634	,"	København V	"));
    array.add(new Postinfo(	1635	,"	København V	"));
    array.add(new Postinfo(	1650	,"	København V	"));
    array.add(new Postinfo(	1651	,"	København V	"));
    array.add(new Postinfo(	1652	,"	København V	"));
    array.add(new Postinfo(	1653	,"	København V	"));
    array.add(new Postinfo(	1654	,"	København V	"));
    array.add(new Postinfo(	1655	,"	København V	"));
    array.add(new Postinfo(	1656	,"	København V	"));
    array.add(new Postinfo(	1657	,"	København V	"));
    array.add(new Postinfo(	1658	,"	København V	"));
    array.add(new Postinfo(	1659	,"	København V	"));
    array.add(new Postinfo(	1660	,"	København V	"));
    array.add(new Postinfo(	1661	,"	København V	"));
    array.add(new Postinfo(	1662	,"	København V	"));
    array.add(new Postinfo(	1663	,"	København V	"));
    array.add(new Postinfo(	1664	,"	København V	"));
    array.add(new Postinfo(	1665	,"	København V	"));
    array.add(new Postinfo(	1666	,"	København V	"));
    array.add(new Postinfo(	1667	,"	København V	"));
    array.add(new Postinfo(	1668	,"	København V	"));
    array.add(new Postinfo(	1669	,"	København V	"));
    array.add(new Postinfo(	1670	,"	København V	"));
    array.add(new Postinfo(	1671	,"	København V	"));
    array.add(new Postinfo(	1672	,"	København V	"));
    array.add(new Postinfo(	1673	,"	København V	"));
    array.add(new Postinfo(	1674	,"	København V	"));
    array.add(new Postinfo(	1675	,"	København V	"));
    array.add(new Postinfo(	1676	,"	København V	"));
    array.add(new Postinfo(	1677	,"	København V	"));
    array.add(new Postinfo(	1699	,"	København V	"));
    array.add(new Postinfo(	1700	,"	København V	"));
    array.add(new Postinfo(	1701	,"	København V	"));
    array.add(new Postinfo(	1702	,"	København V	"));
    array.add(new Postinfo(	1703	,"	København V	"));
    array.add(new Postinfo(	1704	,"	København V	"));
    array.add(new Postinfo(	1705	,"	København V	"));
    array.add(new Postinfo(	1706	,"	København V	"));
    array.add(new Postinfo(	1707	,"	København V	"));
    array.add(new Postinfo(	1708	,"	København V	"));
    array.add(new Postinfo(	1709	,"	København V	"));
    array.add(new Postinfo(	1710	,"	København V	"));
    array.add(new Postinfo(	1711	,"	København V	"));
    array.add(new Postinfo(	1712	,"	København V	"));
    array.add(new Postinfo(	1714	,"	København V	"));
    array.add(new Postinfo(	1715	,"	København V	"));
    array.add(new Postinfo(	1716	,"	København V	"));
    array.add(new Postinfo(	1717	,"	København V	"));
    array.add(new Postinfo(	1718	,"	København V	"));
    array.add(new Postinfo(	1719	,"	København V	"));
    array.add(new Postinfo(	1720	,"	København V	"));
    array.add(new Postinfo(	1721	,"	København V	"));
    array.add(new Postinfo(	1722	,"	København V	"));
    array.add(new Postinfo(	1723	,"	København V	"));
    array.add(new Postinfo(	1724	,"	København V	"));
    array.add(new Postinfo(	1725	,"	København V	"));
    array.add(new Postinfo(	1726	,"	København V	"));
    array.add(new Postinfo(	1727	,"	København V	"));
    array.add(new Postinfo(	1728	,"	København V	"));
    array.add(new Postinfo(	1729	,"	København V	"));
    array.add(new Postinfo(	1730	,"	København V	"));
    array.add(new Postinfo(	1731	,"	København V	"));
    array.add(new Postinfo(	1732	,"	København V	"));
    array.add(new Postinfo(	1733	,"	København V	"));
    array.add(new Postinfo(	1734	,"	København V	"));
    array.add(new Postinfo(	1735	,"	København V	"));
    array.add(new Postinfo(	1736	,"	København V	"));
    array.add(new Postinfo(	1737	,"	København V	"));
    array.add(new Postinfo(	1738	,"	København V	"));
    array.add(new Postinfo(	1739	,"	København V	"));
    array.add(new Postinfo(	1749	,"	København V	"));
    array.add(new Postinfo(	1750	,"	København V	"));
    array.add(new Postinfo(	1751	,"	København V	"));
    array.add(new Postinfo(	1752	,"	København V	"));
    array.add(new Postinfo(	1753	,"	København V	"));
    array.add(new Postinfo(	1754	,"	København V	"));
    array.add(new Postinfo(	1755	,"	København V	"));
    array.add(new Postinfo(	1756	,"	København V	"));
    array.add(new Postinfo(	1757	,"	København V	"));
    array.add(new Postinfo(	1758	,"	København V	"));
    array.add(new Postinfo(	1759	,"	København V	"));
    array.add(new Postinfo(	1760	,"	København V	"));
    array.add(new Postinfo(	1761	,"	København V	"));
    array.add(new Postinfo(	1762	,"	København V	"));
    array.add(new Postinfo(	1763	,"	København V	"));
    array.add(new Postinfo(	1764	,"	København V	"));
    array.add(new Postinfo(	1765	,"	København V	"));
    array.add(new Postinfo(	1766	,"	København V	"));
    array.add(new Postinfo(	1770	,"	København V	"));
    array.add(new Postinfo(	1771	,"	København V	"));
    array.add(new Postinfo(	1772	,"	København V	"));
    array.add(new Postinfo(	1773	,"	København V	"));
    array.add(new Postinfo(	1774	,"	København V	"));
    array.add(new Postinfo(	1775	,"	København V	"));
    array.add(new Postinfo(	1777	,"	København V	"));
    array.add(new Postinfo(	1780	,"	København V	"));
    array.add(new Postinfo(	1785	,"	København V	"));
    array.add(new Postinfo(	1786	,"	København V	"));
    array.add(new Postinfo(	1787	,"	København V	"));
    array.add(new Postinfo(	1790	,"	København V	"));
    array.add(new Postinfo(	1799	,"	København V	"));
    array.add(new Postinfo(	1800	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1801	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1802	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1803	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1804	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1805	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1806	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1807	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1808	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1809	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1810	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1811	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1812	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1813	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1814	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1815	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1816	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1817	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1818	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1819	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1820	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1822	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1823	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1824	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1825	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1826	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1827	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1828	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1829	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1850	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1851	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1852	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1853	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1854	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1855	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1856	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1857	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1860	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1861	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1862	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1863	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1864	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1865	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1866	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1867	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1868	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1870	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1871	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1872	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1873	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1874	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1875	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1876	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1877	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1878	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1879	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1900	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1901	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1902	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1903	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1904	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1905	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1906	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1908	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1909	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1910	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1911	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1912	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1913	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1914	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1915	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1916	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1917	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1920	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1921	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1922	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1923	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1924	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1925	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1926	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1927	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1928	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1950	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1951	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1952	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1953	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1954	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1955	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1956	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1957	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1958	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1959	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1960	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1961	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1962	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1963	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1964	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1965	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1966	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1967	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1970	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1971	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1972	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1973	,"	Frederiksberg C	"));
    array.add(new Postinfo(	1974	,"	Frederiksberg C	"));
    array.add(new Postinfo(	2000	,"	Frederiksberg	"));
    array.add(new Postinfo(	2100	,"	København Ø	"));
    array.add(new Postinfo(	2150	,"	Nordhavn	"));
    array.add(new Postinfo(	2200	,"	København N	"));
    array.add(new Postinfo(	2300	,"	København S	"));
    array.add(new Postinfo(	2400	,"	København NV	"));
    array.add(new Postinfo(	2450	,"	København SV	"));
    array.add(new Postinfo(	2500	,"	Valby	"));
    array.add(new Postinfo(	2600	,"	Glostrup	"));
    array.add(new Postinfo(	2605	,"	Brøndby	"));
    array.add(new Postinfo(	2610	,"	Rødovre	"));
    array.add(new Postinfo(	2620	,"	Albertslund	"));
    array.add(new Postinfo(	2625	,"	Vallensbæk	"));
    array.add(new Postinfo(	2630	,"	Taastrup	"));
    array.add(new Postinfo(	2635	,"	Ishøj	"));
    array.add(new Postinfo(	2640	,"	Hedehusene	"));
    array.add(new Postinfo(	2650	,"	Hvidovre	"));
    array.add(new Postinfo(	2660	,"	Brøndby Strand	"));
    array.add(new Postinfo(	2665	,"	Vallensbæk Strand	"));
    array.add(new Postinfo(	2670	,"	Greve	"));
    array.add(new Postinfo(	2680	,"	Solrød Strand	"));
    array.add(new Postinfo(	2690	,"	Karlslunde	"));
    array.add(new Postinfo(	2700	,"	Brønshøj	"));
    array.add(new Postinfo(	2720	,"	Vanløse	"));
    array.add(new Postinfo(	2730	,"	Herlev	"));
    array.add(new Postinfo(	2740	,"	Skovlunde	"));
    array.add(new Postinfo(	2750	,"	Ballerup	"));
    array.add(new Postinfo(	2760	,"	Måløv	"));
    array.add(new Postinfo(	2765	,"	Smørum	"));
    array.add(new Postinfo(	2770	,"	Kastrup	"));
    array.add(new Postinfo(	2791	,"	Dragør	"));
    array.add(new Postinfo(	2800	,"	Kongens Lyngby	"));
    array.add(new Postinfo(	2820	,"	Gentofte	"));
    array.add(new Postinfo(	2830	,"	Virum	"));
    array.add(new Postinfo(	2840	,"	Holte	"));
    array.add(new Postinfo(	2850	,"	Nærum	"));
    array.add(new Postinfo(	2860	,"	Søborg	"));
    array.add(new Postinfo(	2870	,"	Dyssegård	"));
    array.add(new Postinfo(	2880	,"	Bagsværd	"));
    array.add(new Postinfo(	2900	,"	Hellerup	"));
    array.add(new Postinfo(	2920	,"	Charlottenlund	"));
    array.add(new Postinfo(	2930	,"	Klampenborg	"));
    array.add(new Postinfo(	2942	,"	Skodsborg	"));
    array.add(new Postinfo(	2950	,"	Vedbæk	"));
    array.add(new Postinfo(	2960	,"	Rungsted Kyst	"));
    array.add(new Postinfo(	2970	,"	Hørsholm	"));
    array.add(new Postinfo(	2980	,"	Kokkedal	"));
    array.add(new Postinfo(	2990	,"	Nivå	"));
    array.add(new Postinfo(	3000	,"	Helsingør	"));
    array.add(new Postinfo(	3050	,"	Humlebæk	"));
    array.add(new Postinfo(	3060	,"	Espergærde	"));
    array.add(new Postinfo(	3070	,"	Snekkersten	"));
    array.add(new Postinfo(	3080	,"	Tikøb	"));
    array.add(new Postinfo(	3100	,"	Hornbæk	"));
    array.add(new Postinfo(	3120	,"	Dronningmølle	"));
    array.add(new Postinfo(	3140	,"	Ålsgårde	"));
    array.add(new Postinfo(	3150	,"	Hellebæk	"));
    array.add(new Postinfo(	3200	,"	Helsinge	"));
    array.add(new Postinfo(	3210	,"	Vejby	"));
    array.add(new Postinfo(	3220	,"	Tisvildeleje	"));
    array.add(new Postinfo(	3230	,"	Græsted	"));
    array.add(new Postinfo(	3250	,"	Gilleleje	"));
    array.add(new Postinfo(	3300	,"	Frederiksværk	"));
    array.add(new Postinfo(	3310	,"	Ølsted	"));
    array.add(new Postinfo(	3320	,"	Skævinge	"));
    array.add(new Postinfo(	3330	,"	Gørløse	"));
    array.add(new Postinfo(	3360	,"	Liseleje	"));
    array.add(new Postinfo(	3370	,"	Melby	"));
    array.add(new Postinfo(	3390	,"	Hundested	"));
    array.add(new Postinfo(	3400	,"	Hillerød	"));
    array.add(new Postinfo(	3450	,"	Allerød	"));
    array.add(new Postinfo(	3460	,"	Birkerød	"));
    array.add(new Postinfo(	3480	,"	Fredensborg	"));
    array.add(new Postinfo(	3490	,"	Kvistgård	"));
    array.add(new Postinfo(	3500	,"	Værløse	"));
    array.add(new Postinfo(	3520	,"	Farum	"));
    array.add(new Postinfo(	3540	,"	Lynge	"));
    array.add(new Postinfo(	3550	,"	Slangerup	"));
    array.add(new Postinfo(	3600	,"	Frederikssund	"));
    array.add(new Postinfo(	3630	,"	Jægerspris	"));
    array.add(new Postinfo(	3650	,"	Ølstykke	"));
    array.add(new Postinfo(	3660	,"	Stenløse	"));
    array.add(new Postinfo(	3670	,"	Veksø Sjælland	"));
    array.add(new Postinfo(	3700	,"	Rønne	"));
    array.add(new Postinfo(	3720	,"	Aakirkeby	"));
    array.add(new Postinfo(	3730	,"	Nexø	"));
    array.add(new Postinfo(	3740	,"	Svaneke	"));
    array.add(new Postinfo(	3751	,"	Østermarie	"));
    array.add(new Postinfo(	3760	,"	Gudhjem	"));
    array.add(new Postinfo(	3770	,"	Allinge	"));
    array.add(new Postinfo(	3782	,"	Klemensker	"));
    array.add(new Postinfo(	3790	,"	Hasle	"));
    array.add(new Postinfo(	4000	,"	Roskilde	"));
    array.add(new Postinfo(	4030	,"	Tune	"));
    array.add(new Postinfo(	4040	,"	Jyllinge	"));
    array.add(new Postinfo(	4050	,"	Skibby	"));
    array.add(new Postinfo(	4060	,"	Kirke Såby	"));
    array.add(new Postinfo(	4070	,"	Kirke Hyllinge	"));
    array.add(new Postinfo(	4100	,"	Ringsted	"));
    array.add(new Postinfo(	4130	,"	Viby Sjælland	"));
    array.add(new Postinfo(	4140	,"	Borup	"));
    array.add(new Postinfo(	4160	,"	Herlufmagle	"));
    array.add(new Postinfo(	4171	,"	Glumsø	"));
    array.add(new Postinfo(	4173	,"	Fjenneslev	"));
    array.add(new Postinfo(	4174	,"	Jystrup Midtsj	"));
    array.add(new Postinfo(	4180	,"	Sorø	"));
    array.add(new Postinfo(	4190	,"	Munke Bjergby	"));
    array.add(new Postinfo(	4200	,"	Slagelse	"));
    array.add(new Postinfo(	4220	,"	Korsør	"));
    array.add(new Postinfo(	4230	,"	Skælskør	"));
    array.add(new Postinfo(	4241	,"	Vemmelev	"));
    array.add(new Postinfo(	4242	,"	Boeslunde	"));
    array.add(new Postinfo(	4243	,"	Rude	"));
    array.add(new Postinfo(	4250	,"	Fuglebjerg	"));
    array.add(new Postinfo(	4261	,"	Dalmose	"));
    array.add(new Postinfo(	4262	,"	Sandved	"));
    array.add(new Postinfo(	4270	,"	Høng	"));
    array.add(new Postinfo(	4281	,"	Gørlev	"));
    array.add(new Postinfo(	4291	,"	Ruds Vedby	"));
    array.add(new Postinfo(	4293	,"	Dianalund	"));
    array.add(new Postinfo(	4295	,"	Stenlille	"));
    array.add(new Postinfo(	4296	,"	Nyrup	"));
    array.add(new Postinfo(	4300	,"	Holbæk	"));
    array.add(new Postinfo(	4320	,"	Lejre	"));
    array.add(new Postinfo(	4330	,"	Hvalsø	"));
    array.add(new Postinfo(	4340	,"	Tølløse	"));
    array.add(new Postinfo(	4350	,"	Ugerløse	"));
    array.add(new Postinfo(	4360	,"	Kirke Eskilstrup	"));
    array.add(new Postinfo(	4370	,"	Store Merløse	"));
    array.add(new Postinfo(	4390	,"	Vipperød	"));
    array.add(new Postinfo(	4400	,"	Kalundborg	"));
    array.add(new Postinfo(	4420	,"	Regstrup	"));
    array.add(new Postinfo(	4440	,"	Mørkøv	"));
    array.add(new Postinfo(	4450	,"	Jyderup	"));
    array.add(new Postinfo(	4460	,"	Snertinge	"));
    array.add(new Postinfo(	4470	,"	Svebølle	"));
    array.add(new Postinfo(	4480	,"	Store Fuglede	"));
    array.add(new Postinfo(	4490	,"	Jerslev Sjælland	"));
    array.add(new Postinfo(	4500	,"	Nykøbing Sj	"));
    array.add(new Postinfo(	4520	,"	Svinninge	"));
    array.add(new Postinfo(	4532	,"	Gislinge	"));
    array.add(new Postinfo(	4534	,"	Hørve	"));
    array.add(new Postinfo(	4540	,"	Fårevejle	"));
    array.add(new Postinfo(	4550	,"	Asnæs	"));
    array.add(new Postinfo(	4560	,"	Vig	"));
    array.add(new Postinfo(	4571	,"	Grevinge	"));
    array.add(new Postinfo(	4572	,"	Nørre Asmindrup	"));
    array.add(new Postinfo(	4573	,"	Højby	"));
    array.add(new Postinfo(	4581	,"	Rørvig	"));
    array.add(new Postinfo(	4583	,"	Sjællands Odde	"));
    array.add(new Postinfo(	4591	,"	Føllenslev	"));
    array.add(new Postinfo(	4592	,"	Sejerø	"));
    array.add(new Postinfo(	4593	,"	Eskebjerg	"));
    array.add(new Postinfo(	4600	,"	Køge	"));
    array.add(new Postinfo(	4621	,"	Gadstrup	"));
    array.add(new Postinfo(	4622	,"	Havdrup	"));
    array.add(new Postinfo(	4623	,"	Lille Skensved	"));
    array.add(new Postinfo(	4632	,"	Bjæverskov	"));
    array.add(new Postinfo(	4640	,"	Faxe	"));
    array.add(new Postinfo(	4652	,"	Hårlev	"));
    array.add(new Postinfo(	4653	,"	Karise	"));
    array.add(new Postinfo(	4654	,"	Faxe Ladeplads	"));
    array.add(new Postinfo(	4660	,"	Store Heddinge	"));
    array.add(new Postinfo(	4671	,"	Strøby	"));
    array.add(new Postinfo(	4672	,"	Klippinge	"));
    array.add(new Postinfo(	4673	,"	Rødvig Stevns	"));
    array.add(new Postinfo(	4681	,"	Herfølge	"));
    array.add(new Postinfo(	4682	,"	Tureby	"));
    array.add(new Postinfo(	4683	,"	Rønnede	"));
    array.add(new Postinfo(	4684	,"	Holmegaard	"));
    array.add(new Postinfo(	4690	,"	Haslev	"));
    array.add(new Postinfo(	4700	,"	Næstved	"));
    array.add(new Postinfo(	4720	,"	Præstø	"));
    array.add(new Postinfo(	4733	,"	Tappernøje	"));
    array.add(new Postinfo(	4735	,"	Mern	"));
    array.add(new Postinfo(	4736	,"	Karrebæksminde	"));
    array.add(new Postinfo(	4750	,"	Lundby	"));
    array.add(new Postinfo(	4760	,"	Vordingborg	"));
    array.add(new Postinfo(	4771	,"	Kalvehave	"));
    array.add(new Postinfo(	4772	,"	Langebæk	"));
    array.add(new Postinfo(	4773	,"	Stensved	"));
    array.add(new Postinfo(	4780	,"	Stege	"));
    array.add(new Postinfo(	4791	,"	Borre	"));
    array.add(new Postinfo(	4792	,"	Askeby	"));
    array.add(new Postinfo(	4793	,"	Bogø By	"));
    array.add(new Postinfo(	4800	,"	Nykøbing F	"));
    array.add(new Postinfo(	4840	,"	Nørre Alslev	"));
    array.add(new Postinfo(	4850	,"	Stubbekøbing	"));
    array.add(new Postinfo(	4862	,"	Guldborg	"));
    array.add(new Postinfo(	4863	,"	Eskilstrup	"));
    array.add(new Postinfo(	4871	,"	Horbelev	"));
    array.add(new Postinfo(	4872	,"	Idestrup	"));
    array.add(new Postinfo(	4873	,"	Væggerløse	"));
    array.add(new Postinfo(	4874	,"	Gedser	"));
    array.add(new Postinfo(	4880	,"	Nysted	"));
    array.add(new Postinfo(	4891	,"	Toreby L	"));
    array.add(new Postinfo(	4892	,"	Kettinge	"));
    array.add(new Postinfo(	4894	,"	Øster Ulslev	"));
    array.add(new Postinfo(	4895	,"	Errindlev	"));
    array.add(new Postinfo(	4900	,"	Nakskov	"));
    array.add(new Postinfo(	4912	,"	Harpelunde	"));
    array.add(new Postinfo(	4913	,"	Horslunde	"));
    array.add(new Postinfo(	4920	,"	Søllested	"));
    array.add(new Postinfo(	4930	,"	Maribo	"));
    array.add(new Postinfo(	4941	,"	Bandholm	"));
    array.add(new Postinfo(	4943	,"	Torrig L	"));
    array.add(new Postinfo(	4944	,"	Fejø	"));
    array.add(new Postinfo(	4951	,"	Nørreballe	"));
    array.add(new Postinfo(	4952	,"	Stokkemarke	"));
    array.add(new Postinfo(	4953	,"	Vesterborg	"));
    array.add(new Postinfo(	4960	,"	Holeby	"));
    array.add(new Postinfo(	4970	,"	Rødby	"));
    array.add(new Postinfo(	4983	,"	Dannemare	"));
    array.add(new Postinfo(	4990	,"	Sakskøbing	"));
    array.add(new Postinfo(	5000	,"	Odense C	"));
    array.add(new Postinfo(	5200	,"	Odense V	"));
    array.add(new Postinfo(	5210	,"	Odense NV	"));
    array.add(new Postinfo(	5220	,"	Odense SØ	"));
    array.add(new Postinfo(	5230	,"	Odense M	"));
    array.add(new Postinfo(	5240	,"	Odense NØ	"));
    array.add(new Postinfo(	5250	,"	Odense SV	"));
    array.add(new Postinfo(	5260	,"	Odense S	"));
    array.add(new Postinfo(	5270	,"	Odense N	"));
    array.add(new Postinfo(	5290	,"	Marslev	"));
    array.add(new Postinfo(	5300	,"	Kerteminde	"));
    array.add(new Postinfo(	5320	,"	Agedrup	"));
    array.add(new Postinfo(	5330	,"	Munkebo	"));
    array.add(new Postinfo(	5350	,"	Rynkeby	"));
    array.add(new Postinfo(	5370	,"	Mesinge	"));
    array.add(new Postinfo(	5380	,"	Dalby	"));
    array.add(new Postinfo(	5390	,"	Martofte	"));
    array.add(new Postinfo(	5400	,"	Bogense	"));
    array.add(new Postinfo(	5450	,"	Otterup	"));
    array.add(new Postinfo(	5462	,"	Morud	"));
    array.add(new Postinfo(	5463	,"	Harndrup	"));
    array.add(new Postinfo(	5464	,"	Brenderup Fyn	"));
    array.add(new Postinfo(	5466	,"	Asperup	"));
    array.add(new Postinfo(	5471	,"	Søndersø	"));
    array.add(new Postinfo(	5474	,"	Veflinge	"));
    array.add(new Postinfo(	5485	,"	Skamby	"));
    array.add(new Postinfo(	5491	,"	Blommenslyst	"));
    array.add(new Postinfo(	5492	,"	Vissenbjerg	"));
    array.add(new Postinfo(	5500	,"	Middelfart	"));
    array.add(new Postinfo(	5540	,"	Ullerslev	"));
    array.add(new Postinfo(	5550	,"	Langeskov	"));
    array.add(new Postinfo(	5560	,"	Aarup	"));
    array.add(new Postinfo(	5580	,"	Nørre Aaby	"));
    array.add(new Postinfo(	5591	,"	Gelsted	"));
    array.add(new Postinfo(	5592	,"	Ejby	"));
    array.add(new Postinfo(	5600	,"	Faaborg	"));
    array.add(new Postinfo(	5610	,"	Assens	"));
    array.add(new Postinfo(	5620	,"	Glamsbjerg	"));
    array.add(new Postinfo(	5631	,"	Ebberup	"));
    array.add(new Postinfo(	5642	,"	Millinge	"));
    array.add(new Postinfo(	5672	,"	Broby	"));
    array.add(new Postinfo(	5683	,"	Haarby	"));
    array.add(new Postinfo(	5690	,"	Tommerup	"));
    array.add(new Postinfo(	5700	,"	Svendborg	"));
    array.add(new Postinfo(	5750	,"	Ringe	"));
    array.add(new Postinfo(	5762	,"	Vester Skerninge	"));
    array.add(new Postinfo(	5771	,"	Stenstrup	"));
    array.add(new Postinfo(	5772	,"	Kværndrup	"));
    array.add(new Postinfo(	5792	,"	Årslev	"));
    array.add(new Postinfo(	5800	,"	Nyborg	"));
    array.add(new Postinfo(	5853	,"	Ørbæk	"));
    array.add(new Postinfo(	5854	,"	Gislev	"));
    array.add(new Postinfo(	5856	,"	Ryslinge	"));
    array.add(new Postinfo(	5863	,"	Ferritslev Fyn	"));
    array.add(new Postinfo(	5871	,"	Frørup	"));
    array.add(new Postinfo(	5874	,"	Hesselager	"));
    array.add(new Postinfo(	5881	,"	Skårup Fyn	"));
    array.add(new Postinfo(	5882	,"	Vejstrup	"));
    array.add(new Postinfo(	5883	,"	Oure	"));
    array.add(new Postinfo(	5884	,"	Gudme	"));
    array.add(new Postinfo(	5892	,"	Gudbjerg Sydfyn	"));
    array.add(new Postinfo(	5900	,"	Rudkøbing	"));
    array.add(new Postinfo(	5932	,"	Humble	"));
    array.add(new Postinfo(	5935	,"	Bagenkop	"));
    array.add(new Postinfo(	5953	,"	Tranekær	"));
    array.add(new Postinfo(	5960	,"	Marstal	"));
    array.add(new Postinfo(	5970	,"	Ærøskøbing	"));
    array.add(new Postinfo(	5985	,"	Søby Ærø	"));
    array.add(new Postinfo(	6000	,"	Kolding	"));
    array.add(new Postinfo(	6040	,"	Egtved	"));
    array.add(new Postinfo(	6051	,"	Almind	"));
    array.add(new Postinfo(	6052	,"	Viuf	"));
    array.add(new Postinfo(	6064	,"	Jordrup	"));
    array.add(new Postinfo(	6070	,"	Christiansfeld	"));
    array.add(new Postinfo(	6091	,"	Bjert	"));
    array.add(new Postinfo(	6092	,"	Sønder Stenderup	"));
    array.add(new Postinfo(	6093	,"	Sjølund	"));
    array.add(new Postinfo(	6094	,"	Hejls	"));
    array.add(new Postinfo(	6100	,"	Haderslev	"));
    array.add(new Postinfo(	6200	,"	Aabenraa	"));
    array.add(new Postinfo(	6230	,"	Rødekro	"));
    array.add(new Postinfo(	6240	,"	Løgumkloster	"));
    array.add(new Postinfo(	6261	,"	Bredebro	"));
    array.add(new Postinfo(	6270	,"	Tønder	"));
    array.add(new Postinfo(	6280	,"	Højer	"));
    array.add(new Postinfo(	6300	,"	Gråsten	"));
    array.add(new Postinfo(	6310	,"	Broager	"));
    array.add(new Postinfo(	6320	,"	Egernsund	"));
    array.add(new Postinfo(	6330	,"	Padborg	"));
    array.add(new Postinfo(	6340	,"	Kruså	"));
    array.add(new Postinfo(	6360	,"	Tinglev	"));
    array.add(new Postinfo(	6372	,"	Bylderup-Bov	"));
    array.add(new Postinfo(	6392	,"	Bolderslev	"));
    array.add(new Postinfo(	6400	,"	Sønderborg	"));
    array.add(new Postinfo(	6430	,"	Nordborg	"));
    array.add(new Postinfo(	6440	,"	Augustenborg	"));
    array.add(new Postinfo(	6470	,"	Sydals	"));
    array.add(new Postinfo(	6500	,"	Vojens	"));
    array.add(new Postinfo(	6510	,"	Gram	"));
    array.add(new Postinfo(	6520	,"	Toftlund	"));
    array.add(new Postinfo(	6534	,"	Agerskov	"));
    array.add(new Postinfo(	6535	,"	Branderup J	"));
    array.add(new Postinfo(	6541	,"	Bevtoft	"));
    array.add(new Postinfo(	6560	,"	Sommersted	"));
    array.add(new Postinfo(	6580	,"	Vamdrup	"));
    array.add(new Postinfo(	6600	,"	Vejen	"));
    array.add(new Postinfo(	6621	,"	Gesten	"));
    array.add(new Postinfo(	6622	,"	Bække	"));
    array.add(new Postinfo(	6623	,"	Vorbasse	"));
    array.add(new Postinfo(	6630	,"	Rødding	"));
    array.add(new Postinfo(	6640	,"	Lunderskov	"));
    array.add(new Postinfo(	6650	,"	Brørup	"));
    array.add(new Postinfo(	6660	,"	Lintrup	"));
    array.add(new Postinfo(	6670	,"	Holsted	"));
    array.add(new Postinfo(	6682	,"	Hovborg	"));
    array.add(new Postinfo(	6683	,"	Føvling	"));
    array.add(new Postinfo(	6690	,"	Gørding	"));
    array.add(new Postinfo(	6700	,"	Esbjerg	"));
    array.add(new Postinfo(	6705	,"	Esbjerg Ø	"));
    array.add(new Postinfo(	6710	,"	Esbjerg V	"));
    array.add(new Postinfo(	6715	,"	Esbjerg N	"));
    array.add(new Postinfo(	6720	,"	Fanø	"));
    array.add(new Postinfo(	6731	,"	Tjæreborg	"));
    array.add(new Postinfo(	6740	,"	Bramming	"));
    array.add(new Postinfo(	6752	,"	Glejbjerg	"));
    array.add(new Postinfo(	6753	,"	Agerbæk	"));
    array.add(new Postinfo(	6760	,"	Ribe	"));
    array.add(new Postinfo(	6771	,"	Gredstedbro	"));
    array.add(new Postinfo(	6780	,"	Skærbæk	"));
    array.add(new Postinfo(	6792	,"	Rømø	"));
    array.add(new Postinfo(	6800	,"	Varde	"));
    array.add(new Postinfo(	6818	,"	Årre	"));
    array.add(new Postinfo(	6823	,"	Ansager	"));
    array.add(new Postinfo(	6830	,"	Nørre Nebel	"));
    array.add(new Postinfo(	6840	,"	Oksbøl	"));
    array.add(new Postinfo(	6851	,"	Janderup Vestj	"));
    array.add(new Postinfo(	6852	,"	Billum	"));
    array.add(new Postinfo(	6853	,"	Vejers Strand	"));
    array.add(new Postinfo(	6854	,"	Henne	"));
    array.add(new Postinfo(	6855	,"	Outrup	"));
    array.add(new Postinfo(	6857	,"	Blåvand	"));
    array.add(new Postinfo(	6862	,"	Tistrup	"));
    array.add(new Postinfo(	6870	,"	Ølgod	"));
    array.add(new Postinfo(	6880	,"	Tarm	"));
    array.add(new Postinfo(	6893	,"	Hemmet	"));
    array.add(new Postinfo(	6900	,"	Skjern	"));
    array.add(new Postinfo(	6920	,"	Videbæk	"));
    array.add(new Postinfo(	6933	,"	Kibæk	"));
    array.add(new Postinfo(	6940	,"	Lem St	"));
    array.add(new Postinfo(	6950	,"	Ringkøbing	"));
    array.add(new Postinfo(	6960	,"	Hvide Sande	"));
    array.add(new Postinfo(	6971	,"	Spjald	"));
    array.add(new Postinfo(	6973	,"	Ørnhøj	"));
    array.add(new Postinfo(	6980	,"	Tim	"));
    array.add(new Postinfo(	6990	,"	Ulfborg	"));
    array.add(new Postinfo(	7000	,"	Fredericia	"));
    array.add(new Postinfo(	7007	,"	Fredericia	"));
    array.add(new Postinfo(	7080	,"	Børkop	"));
    array.add(new Postinfo(	7100	,"	Vejle	"));
    array.add(new Postinfo(	7120	,"	Vejle Øst	"));
    array.add(new Postinfo(	7130	,"	Juelsminde	"));
    array.add(new Postinfo(	7140	,"	Stouby	"));
    array.add(new Postinfo(	7150	,"	Barrit	"));
    array.add(new Postinfo(	7160	,"	Tørring	"));
    array.add(new Postinfo(	7171	,"	Uldum	"));
    array.add(new Postinfo(	7173	,"	Vonge	"));
    array.add(new Postinfo(	7182	,"	Bredsten	"));
    array.add(new Postinfo(	7183	,"	Randbøl	"));
    array.add(new Postinfo(	7184	,"	Vandel	"));
    array.add(new Postinfo(	7190	,"	Billund	"));
    array.add(new Postinfo(	7200	,"	Grindsted	"));
    array.add(new Postinfo(	7250	,"	Hejnsvig	"));
    array.add(new Postinfo(	7260	,"	Sønder Omme	"));
    array.add(new Postinfo(	7270	,"	Stakroge	"));
    array.add(new Postinfo(	7280	,"	Sønder Felding	"));
    array.add(new Postinfo(	7300	,"	Jelling	"));
    array.add(new Postinfo(	7321	,"	Gadbjerg	"));
    array.add(new Postinfo(	7323	,"	Give	"));
    array.add(new Postinfo(	7330	,"	Brande	"));
    array.add(new Postinfo(	7361	,"	Ejstrupholm	"));
    array.add(new Postinfo(	7362	,"	Hampen	"));
    array.add(new Postinfo(	7400	,"	Herning	"));
    array.add(new Postinfo(	7430	,"	Ikast	"));
    array.add(new Postinfo(	7441	,"	Bording	"));
    array.add(new Postinfo(	7442	,"	Engesvang	"));
    array.add(new Postinfo(	7451	,"	Sunds	"));
    array.add(new Postinfo(	7470	,"	Karup J	"));
    array.add(new Postinfo(	7480	,"	Vildbjerg	"));
    array.add(new Postinfo(	7490	,"	Aulum	"));
    array.add(new Postinfo(	7500	,"	Holstebro	"));
    array.add(new Postinfo(	7540	,"	Haderup	"));
    array.add(new Postinfo(	7550	,"	Sørvad	"));
    array.add(new Postinfo(	7560	,"	Hjerm	"));
    array.add(new Postinfo(	7570	,"	Vemb	"));
    array.add(new Postinfo(	7600	,"	Struer	"));
    array.add(new Postinfo(	7620	,"	Lemvig	"));
    array.add(new Postinfo(	7650	,"	Bøvlingbjerg	"));
    array.add(new Postinfo(	7660	,"	Bækmarksbro	"));
    array.add(new Postinfo(	7673	,"	Harboøre	"));
    array.add(new Postinfo(	7680	,"	Thyborøn	"));
    array.add(new Postinfo(	7700	,"	Thisted	"));
    array.add(new Postinfo(	7730	,"	Hanstholm	"));
    array.add(new Postinfo(	7741	,"	Frøstrup	"));
    array.add(new Postinfo(	7742	,"	Vesløs	"));
    array.add(new Postinfo(	7752	,"	Snedsted	"));
    array.add(new Postinfo(	7755	,"	Bedsted Thy	"));
    array.add(new Postinfo(	7760	,"	Hurup Thy	"));
    array.add(new Postinfo(	7770	,"	Vestervig	"));
    array.add(new Postinfo(	7790	,"	Thyholm	"));
    array.add(new Postinfo(	7800	,"	Skive	"));
    array.add(new Postinfo(	7830	,"	Vinderup	"));
    array.add(new Postinfo(	7840	,"	Højslev	"));
    array.add(new Postinfo(	7850	,"	Stoholm Jyll	"));
    array.add(new Postinfo(	7860	,"	Spøttrup	"));
    array.add(new Postinfo(	7870	,"	Roslev	"));
    array.add(new Postinfo(	7884	,"	Fur	"));
    array.add(new Postinfo(	7900	,"	Nykøbing M	"));
    array.add(new Postinfo(	7950	,"	Erslev	"));
    array.add(new Postinfo(	7960	,"	Karby	"));
    array.add(new Postinfo(	7970	,"	Redsted M	"));
    array.add(new Postinfo(	7980	,"	Vils	"));
    array.add(new Postinfo(	7990	,"	Øster Assels	"));
    array.add(new Postinfo(	8000	,"	Aarhus C	"));
    array.add(new Postinfo(	8200	,"	Aarhus N	"));
    array.add(new Postinfo(	8210	,"	Aarhus V	"));
    array.add(new Postinfo(	8220	,"	Brabrand	"));
    array.add(new Postinfo(	8230	,"	Åbyhøj	"));
    array.add(new Postinfo(	8240	,"	Risskov	"));
    array.add(new Postinfo(	8245	,"	Risskov Ø	"));
    array.add(new Postinfo(	8250	,"	Egå	"));
    array.add(new Postinfo(	8260	,"	Viby J	"));
    array.add(new Postinfo(	8270	,"	Højbjerg	"));
    array.add(new Postinfo(	8300	,"	Odder	"));
    array.add(new Postinfo(	8305	,"	Samsø	"));
    array.add(new Postinfo(	8310	,"	Tranbjerg J	"));
    array.add(new Postinfo(	8320	,"	Mårslet	"));
    array.add(new Postinfo(	8330	,"	Beder	"));
    array.add(new Postinfo(	8340	,"	Malling	"));
    array.add(new Postinfo(	8350	,"	Hundslund	"));
    array.add(new Postinfo(	8355	,"	Solbjerg	"));
    array.add(new Postinfo(	8361	,"	Hasselager	"));
    array.add(new Postinfo(	8362	,"	Hørning	"));
    array.add(new Postinfo(	8370	,"	Hadsten	"));
    array.add(new Postinfo(	8380	,"	Trige	"));
    array.add(new Postinfo(	8381	,"	Tilst	"));
    array.add(new Postinfo(	8382	,"	Hinnerup	"));
    array.add(new Postinfo(	8400	,"	Ebeltoft	"));
    array.add(new Postinfo(	8410	,"	Rønde	"));
    array.add(new Postinfo(	8420	,"	Knebel	"));
    array.add(new Postinfo(	8444	,"	Balle	"));
    array.add(new Postinfo(	8450	,"	Hammel	"));
    array.add(new Postinfo(	8462	,"	Harlev J	"));
    array.add(new Postinfo(	8464	,"	Galten	"));
    array.add(new Postinfo(	8471	,"	Sabro	"));
    array.add(new Postinfo(	8472	,"	Sporup	"));
    array.add(new Postinfo(	8500	,"	Grenaa	"));
    array.add(new Postinfo(	8520	,"	Lystrup	"));
    array.add(new Postinfo(	8530	,"	Hjortshøj	"));
    array.add(new Postinfo(	8541	,"	Skødstrup	"));
    array.add(new Postinfo(	8543	,"	Hornslet	"));
    array.add(new Postinfo(	8544	,"	Mørke	"));
    array.add(new Postinfo(	8550	,"	Ryomgård	"));
    array.add(new Postinfo(	8560	,"	Kolind	"));
    array.add(new Postinfo(	8570	,"	Trustrup	"));
    array.add(new Postinfo(	8581	,"	Nimtofte	"));
    array.add(new Postinfo(	8585	,"	Glesborg	"));
    array.add(new Postinfo(	8586	,"	Ørum Djurs	"));
    array.add(new Postinfo(	8592	,"	Anholt	"));
    array.add(new Postinfo(	8600	,"	Silkeborg	"));
    array.add(new Postinfo(	8620	,"	Kjellerup	"));
    array.add(new Postinfo(	8632	,"	Lemming	"));
    array.add(new Postinfo(	8641	,"	Sorring	"));
    array.add(new Postinfo(	8643	,"	Ans By	"));
    array.add(new Postinfo(	8653	,"	Them	"));
    array.add(new Postinfo(	8654	,"	Bryrup	"));
    array.add(new Postinfo(	8660	,"	Skanderborg	"));
    array.add(new Postinfo(	8670	,"	Låsby	"));
    array.add(new Postinfo(	8680	,"	Ry	"));
    array.add(new Postinfo(	8700	,"	Horsens	"));
    array.add(new Postinfo(	8721	,"	Daugård	"));
    array.add(new Postinfo(	8722	,"	Hedensted	"));
    array.add(new Postinfo(	8723	,"	Løsning	"));
    array.add(new Postinfo(	8732	,"	Hovedgård	"));
    array.add(new Postinfo(	8740	,"	Brædstrup	"));
    array.add(new Postinfo(	8751	,"	Gedved	"));
    array.add(new Postinfo(	8752	,"	Østbirk	"));
    array.add(new Postinfo(	8762	,"	Flemming	"));
    array.add(new Postinfo(	8763	,"	Rask Mølle	"));
    array.add(new Postinfo(	8765	,"	Klovborg	"));
    array.add(new Postinfo(	8766	,"	Nørre Snede	"));
    array.add(new Postinfo(	8781	,"	Stenderup	"));
    array.add(new Postinfo(	8783	,"	Hornsyld	"));
    array.add(new Postinfo(	8800	,"	Viborg	"));
    array.add(new Postinfo(	8830	,"	Tjele	"));
    array.add(new Postinfo(	8831	,"	Løgstrup	"));
    array.add(new Postinfo(	8832	,"	Skals	"));
    array.add(new Postinfo(	8840	,"	Rødkærsbro	"));
    array.add(new Postinfo(	8850	,"	Bjerringbro	"));
    array.add(new Postinfo(	8860	,"	Ulstrup	"));
    array.add(new Postinfo(	8870	,"	Langå	"));
    array.add(new Postinfo(	8881	,"	Thorsø	"));
    array.add(new Postinfo(	8882	,"	Fårvang	"));
    array.add(new Postinfo(	8883	,"	Gjern	"));
    array.add(new Postinfo(	8900	,"	Randers C	"));
    array.add(new Postinfo(	8920	,"	Randers NV	"));
    array.add(new Postinfo(	8930	,"	Randers NØ	"));
    array.add(new Postinfo(	8940	,"	Randers SV	"));
    array.add(new Postinfo(	8950	,"	Ørsted	"));
    array.add(new Postinfo(	8960	,"	Randers SØ	"));
    array.add(new Postinfo(	8961	,"	Allingåbro	"));
    array.add(new Postinfo(	8963	,"	Auning	"));
    array.add(new Postinfo(	8970	,"	Havndal	"));
    array.add(new Postinfo(	8981	,"	Spentrup	"));
    array.add(new Postinfo(	8983	,"	Gjerlev J	"));
    array.add(new Postinfo(	8990	,"	Fårup	"));
    array.add(new Postinfo(	9000	,"	Aalborg	"));
    array.add(new Postinfo(	9200	,"	Aalborg SV	"));
    array.add(new Postinfo(	9210	,"	Aalborg SØ	"));
    array.add(new Postinfo(	9220	,"	Aalborg Øst	"));
    array.add(new Postinfo(	9230	,"	Svenstrup J	"));
    array.add(new Postinfo(	9240	,"	Nibe	"));
    array.add(new Postinfo(	9260	,"	Gistrup	"));
    array.add(new Postinfo(	9270	,"	Klarup	"));
    array.add(new Postinfo(	9280	,"	Storvorde	"));
    array.add(new Postinfo(	9293	,"	Kongerslev	"));
    array.add(new Postinfo(	9300	,"	Sæby	"));
    array.add(new Postinfo(	9310	,"	Vodskov	"));
    array.add(new Postinfo(	9320	,"	Hjallerup	"));
    array.add(new Postinfo(	9330	,"	Dronninglund	"));
    array.add(new Postinfo(	9340	,"	Asaa	"));
    array.add(new Postinfo(	9352	,"	Dybvad	"));
    array.add(new Postinfo(	9362	,"	Gandrup	"));
    array.add(new Postinfo(	9370	,"	Hals	"));
    array.add(new Postinfo(	9380	,"	Vestbjerg	"));
    array.add(new Postinfo(	9381	,"	Sulsted	"));
    array.add(new Postinfo(	9382	,"	Tylstrup	"));
    array.add(new Postinfo(	9400	,"	Nørresundby	"));
    array.add(new Postinfo(	9430	,"	Vadum	"));
    array.add(new Postinfo(	9440	,"	Aabybro	"));
    array.add(new Postinfo(	9460	,"	Brovst	"));
    array.add(new Postinfo(	9480	,"	Løkken	"));
    array.add(new Postinfo(	9490	,"	Pandrup	"));
    array.add(new Postinfo(	9492	,"	Blokhus	"));
    array.add(new Postinfo(	9493	,"	Saltum	"));
    array.add(new Postinfo(	9500	,"	Hobro	"));
    array.add(new Postinfo(	9510	,"	Arden	"));
    array.add(new Postinfo(	9520	,"	Skørping	"));
    array.add(new Postinfo(	9530	,"	Støvring	"));
    array.add(new Postinfo(	9541	,"	Suldrup	"));
    array.add(new Postinfo(	9550	,"	Mariager	"));
    array.add(new Postinfo(	9560	,"	Hadsund	"));
    array.add(new Postinfo(	9574	,"	Bælum	"));
    array.add(new Postinfo(	9575	,"	Terndrup	"));
    array.add(new Postinfo(	9600	,"	Aars	"));
    array.add(new Postinfo(	9610	,"	Nørager	"));
    array.add(new Postinfo(	9620	,"	Aalestrup	"));
    array.add(new Postinfo(	9631	,"	Gedsted	"));
    array.add(new Postinfo(	9632	,"	Møldrup	"));
    array.add(new Postinfo(	9640	,"	Farsø	"));
    array.add(new Postinfo(	9670	,"	Løgstør	"));
    array.add(new Postinfo(	9681	,"	Ranum	"));
    array.add(new Postinfo(	9690	,"	Fjerritslev	"));
    array.add(new Postinfo(	9700	,"	Brønderslev	"));
    array.add(new Postinfo(	9740	,"	Jerslev J	"));
    array.add(new Postinfo(	9750	,"	Østervrå	"));
    array.add(new Postinfo(	9760	,"	Vrå	"));
    array.add(new Postinfo(	9800	,"	Hjørring	"));
    array.add(new Postinfo(	9830	,"	Tårs	"));
    array.add(new Postinfo(	9850	,"	Hirtshals	"));
    array.add(new Postinfo(	9870	,"	Sindal	"));
    array.add(new Postinfo(	9881	,"	Bindslev	"));
    array.add(new Postinfo(	9900	,"	Frederikshavn	"));
    array.add(new Postinfo(	9940	,"	Læsø	"));
    array.add(new Postinfo(	9970	,"	Strandby	"));
    array.add(new Postinfo(	9981	,"	Jerup	"));
    array.add(new Postinfo(	9982	,"	Ålbæk	"));
    array.add(new Postinfo(	9990	,"	Skagen	"));


    for(int i = 0; i < array.size()-1; i++){

      if(array.get(i).getPostnummere()==Postnr_input) {

        System.out.println("Fundet info: " + array.get(i));
      }

    }



  }

}
